dataset: lastfm
data_path: /home/ece/Desktop/Negative_Sampling/RecBole/recbole/dataset_example
USER_ID_FIELD: user_id
ITEM_ID_FIELD: artist_id

load_col:
  inter: [user_id, artist_id]

epochs: 2
eval_args:
  split:
    RS: [0.8, 0.1, 0.1]
  order: RO
  group_by: user

metrics: [Recall, MRR, NDCG, Hit, Precision, MAP]
valid_metric: MAP@10

mlp_hidden_size: "[128,128]"

learning_rate: 0.001
n_layers: 2
reg_weight: 0.001
train_neg_sample_args:
  distribution: dens
  sample_num: 1

train_batch_size: 2048

learning_rate: 0.01
n_layers: 3
reg_weight: 1e-04
gpu_id: 0
device: 'cuda'
